# Generated by Django 5.2.7 on 2026-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter_sent',
            field=models.BooleanField(default=False, verbose_name='Рассылка отправлена'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на рассылку'),
        ),
    ]
