# Generated by Django 5.2.7 on 2026-06-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_newsletter_sent_user_newsletter_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter_subscribed',
            field=models.BooleanField(default=True, verbose_name='Подписка на рассылку'),
        ),
    ]
